name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  JAVA_VERSION: '11'
  JAVA_DISTRO: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: 'Set up Java'
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: 'Cache Maven packages'
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Build SDK
        run: cd sdk && ./gradlew build publishToMavenLocal

      - name: Build example project
        run: cd examples/apache-maven/custom-pipelines-hello-world && ./mvnw -B clean verify
