#
#  SPDX-License-Identifier: Apache-2.0
#
#  Copyright Decodable, Inc.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      next:
        description: 'Next version'
        required: false

env:
  JAVA_VERSION: '11'
  JAVA_DISTRO: 'temurin'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Set release version
        id: version
        run: |
          BRANCH="release-${{ github.event.inputs.version }}"
          RELEASE_VERSION=${{ github.event.inputs.version }}
          NEXT_VERSION=${{ github.event.inputs.next }}
          PLAIN_VERSION=`echo ${RELEASE_VERSION} | awk 'match($0, /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)/) { print substr($0, RSTART, RLENGTH); }'`
          COMPUTED_NEXT_VERSION="${PLAIN_VERSION}-SNAPSHOT"
          if [ -z $NEXT_VERSION ]
          then
            NEXT_VERSION=$COMPUTED_NEXT_VERSION
          fi
          git checkout -b $BRANCH
          echo "version='$RELEASE_VERSION'" > sdk/gradle.properties
          git config --global user.email "decodable-release-bot@decodable.co.invalid"
          git config --global user.name "decodable-release-bot"
          git commit -a -m "Releasing version $VERSION"
          git push origin $BRANCH
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
          echo "PLAIN_VERSION=$PLAIN_VERSION" >> $GITHUB_ENV

      - name: Build SDK
        run: cd sdk && ./gradlew build publish

      - name: Release SDK
        env:
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.RELEASE_GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.RELEASE_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.RELEASE_GPG_SECRET_KEY }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_BRANCH: ${{ env.BRANCH }}
        run: |
          cd sdk && ./gradlew jreleaserConfig jreleaserFullRelease

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-release
          path: |
            parent/target/jreleaser/trace.log
            parent/target/jreleaser/output.properties

      - name: Set next version
        run: |
          echo "version='$NEXT_VERSION'" > sdk/gradle.properties
          git config --global user.email "decodable-release-bot@decodable.co.invalid"
          git config --global user.name "decodable-release-bot"
          git commit -a -m "Next version ${{ env.NEXT_VERSION }}"
          git push origin ${{ env.BRANCH }}
