#
#  SPDX-License-Identifier: Apache-2.0
#
#  Copyright Decodable, Inc.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      next:
        description: 'Next version'
        required: false

env:
  JAVA_DISTRO: 'temurin'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: |
             11
             20

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Set Release Version
        id: version
        run: |
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          RELEASE_BRANCH="release-${{ github.event.inputs.version }}"
          RELEASE_VERSION=${{ github.event.inputs.version }}
          NEXT_VERSION=${{ github.event.inputs.next }}
          PLAIN_VERSION=`echo ${RELEASE_VERSION} | awk 'match($0, /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)/) { print substr($0, RSTART, RLENGTH); }'`
          COMPUTED_NEXT_VERSION="${PLAIN_VERSION}-SNAPSHOT"
          if [ -z $NEXT_VERSION ]
          then
            NEXT_VERSION=$COMPUTED_NEXT_VERSION
          fi

          git checkout -b $RELEASE_BRANCH
          echo "version=$RELEASE_VERSION" > sdk/gradle.properties
          sed -i 's/^_Version\s.*$/_Version '"$RELEASE_VERSION"'_/g' README.md
          sed -i 's/<version>.*<\/version>/<version>'"$RELEASE_VERSION"'<\/version>/g' README.md
          sed -i 's/implementation \x27co\.decodable:decodable-pipeline-sdk:.*\x27/implementation \x27co.decodable:decodable-pipeline-sdk:'"$RELEASE_VERSION"'\x27/g' README.md
          sed -i 's/<decodable.pipeline.sdk.version>.*<\/decodable.pipeline.sdk.version>/<decodable.pipeline.sdk.version>'"$RELEASE_VERSION"'<\/decodable.pipeline.sdk.version>/g' examples/apache-maven/custom-pipelines-hello-world/pom.xml

          git config --global user.email "decodable-release-bot@decodable.co.invalid"
          git config --global user.name "decodable-release-bot"
          git commit -a -m "Releasing version $RELEASE_VERSION"
          git push origin $RELEASE_BRANCH

          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "RELEASE_BRANCH=$RELEASE_BRANCH" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
          echo "PLAIN_VERSION=$PLAIN_VERSION" >> $GITHUB_ENV

      - name: Build SDK
        run: cd sdk && ./gradlew build publishToMavenLocal publish

      - name: Build Example Project
        run: cd examples/apache-maven/custom-pipelines-hello-world && ./mvnw -B clean verify

      - name: Release SDK
        env:
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.RELEASE_GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.RELEASE_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.RELEASE_GPG_SECRET_KEY }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_BRANCH: ${{ env.RELEASE_BRANCH }}
        run: |
          cd sdk && ./gradlew jreleaserConfig jreleaserFullRelease

      - name: Prepare API Docs Publication
        run: |
          mkdir -p sdk/build/docs/decodable-pipeline-sdk/api-docs
          mv sdk/build/docs/javadoc sdk/build/docs/decodable-pipeline-sdk/api-docs/current

      - name: Publish API Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sdk/build/docs/decodable-pipeline-sdk

      - name: JReleaser Output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-release
          path: |
            sdk/build/jreleaser/trace.log
            sdk/build/jreleaser/output.properties

      - name: Set Next Version
        run: |
          echo "version=$NEXT_VERSION" > sdk/gradle.properties
          git config --global user.email "decodable-release-bot@decodable.co.invalid"
          git config --global user.name "decodable-release-bot"
          git commit -a -m "Next version ${{ env.NEXT_VERSION }}"
          git checkout ${{ env.BRANCH }}
          git merge ${{ env.RELEASE_BRANCH }}
          git push origin ${{ env.BRANCH }}
          git push origin :${{ env.RELEASE_BRANCH }}
